# lib/web/10-overview.jq — the org at a glance: how old every reading is and
# what refreshes it, the counts, the latest week's figures, what advise ranks
# first. Input `.` is the sources object lib/web.sh builds (docs/web.md).
#
# Every figure the overview shows is computed here (rule 3), and every one is
# handed to the page with the file it came from, so the view can put the path
# in a title attribute. The week's figures are lib/stats.jq's, already run by
# lib/web.sh over the newest cache/prs file — nothing is recomputed from prose.
#
# The map is the overview's main source: with no graph.json there is nothing
# to overview, and the panel says which command makes one.

.map.graph as $g
| if $g == null then {generated: null, missing: "orgami scan"} else

($g.generated // null) as $mapped

# One row of the readings table. A reading older than the map is marked stale
# (rule 4): the map is the thing the others describe, so a reading taken
# before the last scan may describe repositories the map no longer has.
| def reading($id; $label; $file; $gen; $cmd; $present):
    {id: $id, label: $label, file: $file, command: $cmd, present: $present,
     generated: (if $present then $gen else null end),
     stale: ($present and $gen != null and $mapped != null and $gen < $mapped)};

# A tally over a list of labels: [{name, count}], largest first, name second
# so two runs order the same (rule 7).
  def tally: group_by(.) | map({name: .[0], count: length}) | sort_by(-.count, .name);

  ($g.nodes // []) as $nodes
| ($g.edges // []) as $edges
| [$nodes[] | select(.kind == "repo")] as $repos
| .map.live as $live
| .map.advise as $advise

# The latest recap and the latest daily digest are markdown, so their date is
# the one their own footer carries — `Generated by orgami on <day>` for a
# week, `<!-- orgami daily · generated <iso> -->` for a day. A recap with no
# footer falls back to its week's `until` from the cache.
| ([.reports[] | select(.file | test("^reports/[0-9]{4}-W[0-9]{2}\\.md$"))] | last) as $recap
| ($recap.file // "" | capture("reports/(?<w>[0-9]{4}-W[0-9]{2})\\.md") // {} | .w) as $recap_week
| (if $recap == null then null else
     (([$recap.text | capture("Generated by [^\n]*? on (?<d>[0-9]{4}-[0-9]{2}-[0-9]{2})")] | .[0].d)
      // ([.weeks[] | select(.week == $recap_week) | .until] | .[0])
      // null) end) as $recap_date
| (.daily | last) as $digest
| (if $digest == null then null else
     (([$digest.text | capture("orgami daily · generated (?<d>[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]+Z)")] | .[0].d)
      // ($digest.file | capture("daily/(?<d>[0-9]{4}-[0-9]{2}-[0-9]{2})\\.md") // {} | .d)
      // null) end) as $digest_date

# The newest week in the cache, with the figures stats.jq computed for it.
| (.weeks | last) as $week
| ($week.stats // null) as $stats

| {
    generated: $mapped,
    command: "orgami scan",

    org: {name: $company, slug: $org,
          docs_repo: (.config.docs_repo // null),
          docs_path: (.config.docs_path // null),
          mapped: $mapped, file: "map/graph.json"},

    # Every reading orgami takes, present or not, in the order the tool's
    # menu lists the commands. repos.json is written by the same scan that
    # writes graph.json and carries no date of its own, so it takes the map's.
    readings: [
      reading("map";      "map";          "map/graph.json";    $mapped;                      "orgami scan";     true),
      reading("profiles"; "profiles";     "map/repos.json";    $mapped;                      "orgami scan";     (.map.repos != null)),
      reading("live";     "live";         "map/live.json";     ($live.generated // null);    "orgami live";     ($live != null)),
      reading("dns";      "dns";          "map/dns.json";      (.map.dns.generated // null); "orgami dns";      (.map.dns != null)),
      reading("advise";   "advise";       "map/advise.json";   ($advise.generated // null);  "orgami advise";   ($advise != null)),
      reading("coupling"; "coupling";     "map/coupling.json"; (.map.coupling.generated // null); "orgami coupling"; (.map.coupling != null)),
      reading("depth";    "depth";        "map/depth.json";    (.map.depth.generated // null);    "orgami depth";    (.map.depth != null)),
      reading("recap";    "latest recap"; ($recap.file // "reports/<week>.md"); $recap_date;  "orgami report";   ($recap != null)),
      reading("daily";    "latest daily"; ($digest.file // "reports/daily/<date>.md"); $digest_date; "orgami daily"; ($digest != null))
    ],

    counts: {
      file: "map/graph.json",
      repos: {total: ($repos | length),
              by_language: ([$repos[] | .meta.language // "not found"] | tally)},
      nodes: {total: ($nodes | length),
              by_kind: ([$nodes[] | .kind] | tally)},
      # Extracted and inferred kept apart on every kind (rule 2): a
      # changes-with edge and a deploys-to edge are not the same sort of fact.
      edges: {total: ($edges | length),
              extracted: ([$edges[] | select((.confidence // "extracted") != "inferred")] | length),
              inferred: ([$edges[] | select((.confidence // "extracted") == "inferred")] | length),
              by_kind: ($edges | group_by(.kind)
                        | map({name: .[0].kind,
                               extracted: ([.[] | select((.confidence // "extracted") != "inferred")] | length),
                               inferred: ([.[] | select((.confidence // "extracted") == "inferred")] | length),
                               count: length})
                        | sort_by(-.count, .name))},
      vendors: {total: ([$nodes[] | select(.kind == "vendor")] | length),
                by_category: ([$nodes[] | select(.kind == "vendor") | .meta.category // "not found"] | tally)},
      hosts: {total: ([$nodes[] | select(.kind == "host")] | length)},
      # What the providers answered, when somebody has asked them.
      live: (if $live == null then null else
              {file: "map/live.json", generated: ($live.generated // null),
               matched: (($live.deployments // []) | length),
               unmatched: (($live.unmatched // []) | length),
               providers: ($live.providers // [])} end)
    },

    # The newest week's figures, as stats.jq computed them. `authors` is the
    # size of the by_author table stats.jq already built — no new figure.
    week: (if $week == null then null else
            {file: $week.file, week: $week.week, since: $week.since, until: $week.until,
             report: (if $recap_week == $week.week then $recap.file else null end),
             figures: (if $stats == null then null else
               {merged: $stats.merged,
                merged_by_bots: $stats.merged_by_bots,
                authors: ($stats.by_author // {} | keys | length),
                repos_touched: $stats.repos_touched,
                median_hours_to_merge: $stats.median_hours_to_merge,
                merged_without_review: $stats.merged_without_review,
                lines_added: $stats.lines_added,
                lines_removed: $stats.lines_removed} end)} end),

    # What advise ranks first: the three open proposals with the lowest rank,
    # in advise.json's own order. Blast radius is repositories then domains,
    # the way lib/advise.jq sorts.
    advise: (if $advise == null then null else
              {file: "map/advise.json", generated: ($advise.generated // null),
               proposals: ($advise.counts.proposals // 0),
               suppressed: ($advise.counts.suppressed // 0),
               top: ([($advise.proposals // [])[] | select(.suppressed | not)]
                     | sort_by(.rank) | .[0:3]
                     | map({id, kind, rank, confidence, claim,
                            repo_count: (.repo_count // 0),
                            domain_count: ((.domains // []) | length),
                            vendors: (.vendors // []),
                            candidate: (.candidate // (.vendors // [])[0] // null)}))} end)
  }
end
